function [BOS, edge_map, occ_map, group_map] = runFGSeparation(stimulus, params, options)
%RUNFGSEPARATION Run the FG Separation Model on the specified stimulus
% Inputs:
% stimulus: 2D numerical array
% params: parameters, generated by makeParams()
% options.attention: array (optional)
% options.debug: Boolean, if true debug figures will be displayed (optional)
% options.log_dir: debug figures will be saved to this directory (optional)
%
% Outputs:
% BOS (Border Ownership Signal): mxnx3 Matrix (mxn=model dimensions (equivalent to stimulus dimensions), 3: HSV-values)
% H - range [0,1] (encodes [0,2pi]) -> BOS-direction
% S - normalized strength of BOS-Signal
% V - 1
% edge_map: edge detection results
% occ_map: BOS as RGB image
% group_map: summed G-Cell activities

arguments
    stimulus
    params
    options.attention = []
    options.debug (1,1) logical = false
    options.log_dir = ""
end
save = ~isempty(options.log_dir) && strlength(options.log_dir) > 0;

if isempty(options.attention)
    options.attention = squeeze(ones(1,params.num_scales))/params.num_scales;
elseif length(options.attention) ~= params.num_scales
    error("attention array must have the same length as number of scales!");
end
if sum(options.attention) ~= 1
    options.attention = options.attention/sum(options.attention);
end
options.attention = options.attention*params.num_scales - 1;


%% Initialize
dimensions = size(stimulus);

B1 = zeros(params.num_ori, dimensions(1), dimensions(2));
B2 = zeros(params.num_ori, dimensions(1), dimensions(2));
E = zeros(params.num_ori, dimensions(1), dimensions(2));
G = zeros(params.num_scales, dimensions(1), dimensions(2));

% corfresponse contains contrasts, oriensMatrix contains the orientation of
% contrasts at each spatial location
[~,~,corfresponse,oriensMatrix] = CORFContourDetection(stimulus,2.2,4,1.8);
oriensMatrix = mod(round(oriensMatrix/(2*pi)*16)+4,16)+1; % convert orientations to indices

filt = zeros(8, 120, 120);
for ori=1:params.num_ori
    % Combine opposite contrast polarities at each orientation
    E(ori, :, :) = corfresponse.*(oriensMatrix==ori) + corfresponse.*(oriensMatrix==ori+8);
    filt(ori,:,:) = gaussianFilter2D(120, 120, 40, 40);
end
% Normalize E cell responses
E_norm = imfilter(squeeze(sum(E, 1)), gaussianFilter2D(15, 15, 5, 5));
for ori=1:params.num_ori
    E(ori, :, :) = squeeze(E(ori, :, :))./(0.01 + 5*E_norm);
end
E = E*params.E_scale;

if options.debug
    % Initialize arrays to store average B activities and BOS-Signals
    avgB_over_iterations = zeros(1, params.iterations);
    BOS_over_iterations = zeros(params.iterations, dimensions(1), dimensions(2), 3);
    G_over_iterations = zeros(params.iterations, dimensions(1), dimensions(2));
end

%% Run Model
for idx=1:params.iterations % Loop through all iterations
    if ~options.debug || idx ~= params.iterations
        [B1, B2] = calculateBCellActivities(E, B1, B2, G, params, false);
    else
        [B1, B2] = calculateBCellActivities(E, B1, B2, G, params, true);
    end
    G = calculateGCellActivities(B1, B2, params, options.attention);

    if options.debug
        % Average B1 and B2 over orientations and the entire array (calculate one scalar)
        avgB_over_iterations(idx) = mean(cellfun(@(x) mean(x(:)), {B1})) + mean(cellfun(@(x) mean(x(:)), {B2}));
        % BOS-Signal
        BOS_over_iterations(idx,:,:,:) = getBOS(B1, B2, params, "unnormalized");
        G_over_iterations(idx,:,:) = squeeze(sum(G, 1));
    end
end

%% Output
BOS = getBOS(B1, B2, params);
edge_map = corfresponse;
occ_map = hsv2rgb(BOS);
group_map = squeeze(sum(G));

%% Debug
if options.debug
    if save
        if ~exist(options.log_dir, 'dir')
            mkdir(options.log_dir);
        end
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % FB Segmentation (already generated)
    if save  && params.B.integration_mode == "max"
        saveas(gcf, fullfile(options.log_dir, 'FB_segmentation.png'));
    end

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % 2D graph for average B activity
    figure;
    plot(1:params.iterations, avgB_over_iterations, '-o', 'LineWidth', 2);
    title('Average B Activity Over Iterations');
    xlabel('Iteration');
    ylabel('Average Activity');
    grid on;
    
    if save
        saveas(gcf, fullfile(options.log_dir, 'average_B_activity.png'));
    end
    
    %%%%%%%%%%%%%%%%%%%%%
    % BOS over iterations
    BOS_over_iterations(:,:,:,2) = BOS_over_iterations(:,:,:,2)/max(BOS_over_iterations(:,:,:,2), [], "all"); % normalize over all iterations
    figure; tiledlayout(1, 10, 'TileSpacing','compact','Padding','compact');
    selected_iterations = round(linspace(1, params.iterations, 10));
    for idx=1:10
        nexttile(idx);
        imagesc(hsv2rgb(squeeze(BOS_over_iterations(selected_iterations(idx),:,:,:))));
        axis image;
        title(['Iteration: ', num2str(selected_iterations(idx))]);
    end
    sgtitle('BOS over iterations', 'FontWeight', 'bold');
    set(gcf, "Position", [100,100,300*10,270]);
    if save
        saveas(gcf, fullfile(options.log_dir, 'BOS_development.png'));
    end

    %%%%%%%%%%%%%%%%%%%
    % G over iterations
    figure; tiledlayout(1, 10, 'TileSpacing','compact','Padding','compact');
    selected_iterations = round(linspace(1, params.iterations, 10));
    G_clim = [0, max(G_over_iterations, [], "all")];
    for idx=1:10
        nexttile(idx);
        imagesc(squeeze(G_over_iterations(selected_iterations(idx),:,:)));
        axis image;
        title(['Iteration: ', num2str(selected_iterations(idx))]);
        colorbar;
        clim(G_clim);
    end
    sgtitle('G-Cell activity over iterations', 'FontWeight', 'bold');
    set(gcf, "Position", [100,100,320*10,270]);
    if save
        saveas(gcf, fullfile(options.log_dir, 'G_development.png'));
    end
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % G-activity on a scale-individual basis
    figure; tiledlayout(2, 3, 'TileSpacing', 'compact', 'Padding', 'tight');
    G_clim = [0, max(G, [], "all")];
    for k=1:params.num_scales
        nexttile(k);
        imagesc(squeeze(G(k,:,:))); colorbar;
        axis image;
        title(['R = ', num2str(params.R0*params.scale_step^(k-1))]);
        clim(G_clim);
    end
    sgtitle('G-Cell activity per scale (R = RF radius)', 'FontWeight', 'bold');
    set(gcf, 'Position', [50, 50, 1140, 620]);
    if save
        saveas(gcf, fullfile(options.log_dir, 'G_scale-individual.png'));
    end
    
    %%%%%%%%%%%%%%%%%%%%%%%%
    % Summed G-Cell activity
    figure; imagesc(squeeze(sum(G, 1))); colorbar;
    axis image;
    if save
        saveas(gcf, fullfile(options.log_dir, 'summed_G.png'));
    end
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Collapsed Scales BOS-Signal
    figure; imagesc(hsv2rgb(getBOS(B1, B2, params)));
    axis image;
    if save
        saveas(gcf, fullfile(options.log_dir, 'BOS.png'));
    end
    
    %%%%%%%%%%
    % Stimulus
    figure; imagesc(stimulus); colormap(gray); colorbar;
    axis image;
    if save
        saveas(gcf, fullfile(options.log_dir, 'stimulus.png'));
    end
    
    %%%%%%%%%%%%%%%%
    % Edge Detection
    figure; imagesc(corfresponse); axis image; colormap(gray); colorbar;
    axis image;
    if save
        saveas(gcf, fullfile(options.log_dir, 'edge_detection.png'));
    end
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % B-Cell activity and BOS-Signal split for orientation
    figure; 
    tiledlayout(3, 8, 'TileSpacing', 'tight', 'Padding', 'tight');

    % Precompute limits
    B_values = [];
    BOS_values = [];
    for ori = 1:8
        B_values = [B_values; squeeze(B1(ori, :, :)); squeeze(B2(ori, :, :))];
        BOS_values = [BOS_values; squeeze(B1(ori, :, :)) - squeeze(B2(ori, :, :))];
    end
    B_clim = [0, max(B_values, [], "all")];
    BOS_clim = [min(BOS_values, [], "all"), max(BOS_values, [], "all")];

    for ori = 1:params.num_ori
        nexttile(ori); % First row
        imagesc(squeeze(B1(ori,:,:)));
        axis image;
        title(['B1 \theta=', num2str(ori)]);
        colorbar;
        clim(B_clim);
    
        nexttile(ori + 8); % Second row
        imagesc(squeeze(B2(ori,:,:)));
        axis image;
        title(['B2 \theta=', num2str(ori)]);
        colorbar;
        clim(B_clim);
    
        nexttile(ori + 16); % Third row
        BOS_signal = squeeze(B1(ori,:,:))-squeeze(B2(ori,:,:));
        imagesc(BOS_signal);
        axis image;
        title(['BOS \theta=', num2str(ori)]);
        colorbar;
        clim(BOS_clim);
    end
    set(gcf, 'Position', [50, 50, 1800, 500]);
    if save
        saveas(gcf, fullfile(options.log_dir, 'B_BOS.png'));
    end

    %% Parameters
    % --- Parameter Figure ---
    figure('Name', 'Parameters', 'Position', [100, 100, 450, 700]);
    
    % Create parameter string with proper formatting
    paramText = sprintf([...
        '\\fontsize{16}\\bfModel Parameters\n\n' ...
        '\\fontsize{12}\\bfB Cell Parameters:\\rm\n' ...
        '    \\alpha_B = %.2f\n' ...
        '    \\beta_B = %.2f\n' ...
        '    \\gamma_B = %.2f\n' ...
        '    \\zeta_B = %.2f\n' ...
        '    \\lambda_B = %.2f\n' ...
        '    \\mu_B = %.2f\n' ...
        '    \\nu_B = %.2f\n' ...
        '\\fontsize{12}\\bfG Cell Parameters:\\rm\n' ...
        '    \\alpha_G = %.2f\n' ...
        '    \\beta_G = %.2f\n' ...
        '    \\gamma_G = %.2f\n' ...
        '    \\zeta_G = %.2f\n' ...
        '    \\mu_G = %.2f\n' ...
        '    \\nu_G = %.2f\n' ...
        '\\fontsize{12}\\bfSimulation:\\rm\n' ...
        '    Iterations = %d\n' ...
        '    # orientations = %d\n' ...
        '    # scales = %d\n' ...
        '    filter type = %s\n' ...
        '    integration mode = %s'], ...
        params.B.alpha, params.B.beta, params.B.gamma, params.B.zeta, params.B.lambda, params.B.mu, params.B.nu, ...
        params.G.alpha, params.G.beta, params.G.gamma, params.G.zeta, params.G.mu, params.G.nu, ...
        params.iterations, params.num_ori, params.num_scales, params.filter_type, params.B.integration_mode);
    
    % Create axes that fills the figure
    ax = axes('Position', [0.05 0.05 0.9 0.9], 'Visible', 'off');
    xlim([0 1]);
    ylim([0 1]);
    
    % Add background rectangle with padding
    rectangle('Position', [0.05 0.05 0.9 0.9], ...
        'FaceColor', [0.95 0.95 0.95], ...
        'EdgeColor', 'black', ...
        'LineWidth', 2);
    
    % Add text with proper positioning
    text(0.5, 0.95, paramText, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'FontName', 'FixedWidth', ...
        'FontSize', 11, ...
        'Interpreter', 'tex');
    
    axis off;
    if save
        saveas(gcf, fullfile(options.log_dir, 'parameters.png'));
    end
end
end

